language: node_js
git:
  depth: false
node_js:
  - "10"

cache:
  directories:
    - node_modules # NPM packages

services:
    - docker

install:
    - npm install

script:
    - echo $TRAVIS_COMMIT_RANGE
    - npm run eslintdiff
